### PR TITLE
Fullstack validation

### PR DESCRIPTION
**Pull request by internet-diglett**
- [x] Build Dendrite for Softnpu
- [x] Include Dendrite
- [x] Build propolis with softnpu support
- [x] Build softnpuadm
- [x] Include softnpuadm
- [x] Build p4 program
- [x] Include p4 program
- [x] Launch fullstack topology with custom propolis
- [x] Install p4 program on scrimlets
- [x] Install softnpuadm on scrimlets
- [x] Install Dendrite w/ softnup support on Scrimlet nodes
- [x] Test connectivity between sleds
- [x] Add gateway node
- [x] Test boundary services
- [x] Test connectivity between sled guests
- [x] Enable second scrimlet / sidecar node
- [x] Validate multipath

### CODE REVIEW

**Comment by internet-diglett** [comment]
Due to all of the special variants of binaries needed to run `softnpu`, the `netstack-prepare` task is doing quite a bit of compilation in sequence. Will probably look into breaking the prepare task into separate, smaller tasks that build each binary separately.

**Review by rcgoodfellow — APPROVED** [review]
This looks great. Lot's of moving parts here!

Looking at the CI output, I'd suggest setting RUST_LOG=debug so we can see the output from commands that are orchestrated in the falcon topology definition in the buildomat readout.

**Comment by internet-diglett** [comment]
> Looking at the CI output, I'd suggest setting RUST_LOG=debug so we can see the output from commands that are orchestrated in the falcon topology definition in the buildomat readout.

This is a good idea. I'll add that to the scripts.

**Review by rcgoodfellow — APPROVED** [review]
Looks great. Thanks!

**Pull request merged**
